### ISSUE TITLE
LGPL-3.0 source header remaining after relicense

### ISSUE THREAD

**Issue by hyandell** [vlsi/compactmap#10]
Hi Vladimir,

The https://github.com/vlsi/compactmap/blob/master/compactmap/src/main/java/vlsi/utils/CompactHashMapClassEmptyDefaults.java file still has the old LGPL-3.0 source header on it, in addition to the Apache-2.0 new header. Was this intentional?

**Comment by vlsi** [comment]
That is weird. Will fix it

**Comment by hyandell** [comment]
Thank you :)
