### ISSUE TITLE
onsavedinstancestate restoreinstancestate issue

### ISSUE THREAD

**Issue by AhmedX6** [vlsi/compactmap#8]
Hello,

when storing large map onSavedInstanceState it crashes with TransactionTooLargeException.

Do you have any solution ?

**Comment by vlsi** [comment]
Could you clarify/provide steps to reproduce?

**Comment by AhmedX6** [comment]
Hello,

![image](https://user-images.githubusercontent.com/13573148/172027415-6bd840f8-8cf7-446c-bdee-640966f2cecc.png)

Here I this crash:

!!! FAILED BINDER TRANSACTION !!!  (parcel size = 45086448)

I have a large amount of data on this map. Is it possible to compress it ?

**Comment by vlsi** [comment]
I guess it is a duplicate of https://github.com/vlsi/compactmap/issues/9, and it should probably be resolved in 2.0.1
